version: '2.1'
orbs:
  gh-pages: sugarshin/gh-pages@1.0.1
jobs:
  build_deploy:
    executor: gh-pages/default
    steps:
      - checkout
      - run: ./build.sh
      - gh-pages/deploy:
          setup-git: true
          ssh-fingerprints: 8a:10:e8:70:04:05:dd:d3:c7:3a:6d:56:86:45:64:70
workflows:
  Build and Deploy:
    jobs:
      - build_deploy
